### ISSUE TITLE
Cardiod Write-up

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#123]
@hauten, can we get this https://github.com/llnl/cardiod linked in with other write-ups about it?

Also, we probably want to link the Cardiod README back to other press it got circa 2012.

cc/ @gonsie @rblake-llnl

**Comment by hauten** [comment]
Fixed by two PRs:
1. https://github.com/LLNL/cardioid/pull/2 (added "Learn more" content to Cardioid README)
2. https://github.com/LLNL/llnl.github.io/pull/126 (added Cardioid repo info to portal news)

However, we do not have a writeup about Cardioid on https://computation.llnl.gov/projects that provides another way to get to the repo w/ associated context. I'll work on that outside of GitHub and ask @rblake-llnl to review/approve. We can also tweet about it.

**Comment by IanLee1521** [comment]
Since the two PRs are now merged, it seems like we can close this.
