### ISSUE TITLE
RADIUSS Page

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#151]
This is a top-level issue for tracking integration of RADIUSS documentation / resources.

Current idea:

- RADIUSS overview computation.llnl.gov "Computation stands behind RADIUSS"
- Sub-page under software.llnl.gov that has all the dynamic details for "how to integrate / user with RADIUSS" (software.llnl.gov/radiuss ?)
- RADIUS project / team details on internal dev.llnl.gov site.

**Comment by davidbeckingsale** [comment]
Do we want the overview and the details to be at the same URL?

**Comment by cyrush** [comment]
seems we could have a `llnl/radiuss` project to host website source and website, etc?

**Comment by IanLee1521** [comment]
I was thinking it would just live in this repo.

**Comment by cyrush** [comment]
hmm, i think the future we will have sphinx docs, code examples - for things that showcase using multiple radiuss products. They may even need CI checks, etc. Not sure it would make sense to have all of that in this repo.

**Comment by IanLee1521** [comment]
True. Some of those I would think might live in the "real" repos (like blt, spack, etc).

**Comment by IanLee1521** [comment]
@hauten -- 

https://github.com/LLNL/llnl.github.io/blob/master/explore/github-data/labReposInfo.json is the "master" json file that gets updated from @LRWeber 's script based on all of the orgs and repos from https://github.com/LLNL/llnl.github.io/blob/master/_explore/input_lists.json

I also created https://github.com/LLNL/llnl.github.io/tree/radiuss with a new `radiuss/index.html` that you should be able to modify to make work with the static data for RADIUSS projects.

**Comment by cyrush** [comment]
@IanLee1521 many projects have those types of materials, however we will need a place that hosts integration examples that will be more cross cutting. We can still create that repo for that purpose of course.

**Comment by hauten** [comment]
> @hauten --
> 
> https://github.com/LLNL/llnl.github.io/blob/master/explore/github-data/labReposInfo.json is the "master" json file that gets updated from @LRWeber 's script based on all of the orgs and repos from https://github.com/LLNL/llnl.github.io/blob/master/_explore/input_lists.json
> 
> I also created https://github.com/LLNL/llnl.github.io/tree/radiuss with a new `radiuss/index.html` that you should be able to modify to make work with the static data for RADIUSS projects.

And reminder to myself to update the nav

**Comment by hauten** [comment]
@gonsie would you be able to help me this week or next? i have this partially figured out.

**Comment by gonsie** [comment]
FYI: a repo can have up to 20 tags.

**Comment by hauten** [comment]
Bullet 2, PR #157 will result in software.llnl.gov/radiuss

Bullet 1, RADIUSS overview computation.llnl.gov "Computation stands behind RADIUSS" - I drafted content for comp external, comp internal, & hpc.llnl.gov (linking to software.llnl.gov/radiuss) - sending to Rob for review

In other words, the portal and "marketing" pieces are nearly done. That leaves Bullet 3 re: dev.llnl.gov or new repo or however it should be handled.

**Comment by hauten** [comment]
Bullet 1 is done:
https://hpc.llnl.gov/radiuss
https://computation.llnl.gov/projects/radiuss

**Comment by hauten** [comment]
Revised plan as of 6/19 (see also issue #17):

1. Redirect radiuss.llnl.gov to software.llnl.gov/radiuss - thus keeping radiuss work on the portal and within this repo
2. Update Comp & HPC pages with new URL
3. Update /radiuss "home page" with new design (6 categories but no "open source" header)
4. Pull in 'radiuss'-tagged repos by category
5. Build out radiuss sub-pages according to LC Confluence content (e.g., About RADIUSS, Best Practices)

**Comment by IanLee1521** [comment]
@hauten -- Looks like we got all the topics added.

**Comment by steveg21** [comment]
In the intermediate/long term, the page referenced by bullet #2 (software.llnl.gov/radius) will need to be modified to somehow reference specific RADIUSS releases.  It's handy to have links to the various repos, but there's no way to guarantee that arbitrary versions of all RADIUSS products will work together.  
Relevant examples are CEED (https://ceed.exascaleproject.org/ceed-2.0/) and xSDK (https://xsdk.info/releases/)  
As @cyrush points out, a separate repo will likely be needed to manage releases.

**Comment by IanLee1521** [comment]
@steveg21 - I'm still not convinced that a separate repo is necessary or a good idea for this. I really feel strongly that we should start by building those examples (and versioning how RADIUSS as a collection fits together) on this site under the `/radiuss/` subtree. 

For instance you could build a page like that CEED 2.0 page at something like `https://software.llnl.gov/radiuss/v1/` showing how all the RADIUSS products fit together.

**Comment by tzanio** [comment]
If this is helpful, the CEED 2.0 is just one markdown file in the CEED web repo, which is generated by MkDocs, similarly to https://github.com/mfem/web.

I can give you access if you want to see the source.

**Comment by steveg21** [comment]
@IanLee1521 - I agree, let's use the existing repo unless things evolve and a need to create a new one arises.

**Comment by cyrush** [comment]
@IanLee1521 @steveg21 that sounds good -  especially if this starts as documentation.

For context, here is the dream scenario that I think would req using an other repo:

- clone a radiuss repo
- build all tpls with magic script that works on lc platforms
- hop into dirs with ready made examples, build and go

This would involve revision controlling many non-documentation things and also extensive CI testing. All which wouldn't make sense to hoist upon the software portal website repo.

**Comment by adrienbernede** [comment]
Hi all,

Thank you for participating in this debate, as it provides me with useful information for helping designing the RADIUSS guidelines and release plan.

Different aspects of the project have been mentioned so far, and I think this is why it may seem complicated to find an immediate and satisfying solution.

The short (though far from complete) version of the following comments could be :
**I agree with the idea of having the policy and project status versioned here, and the work done building and testing the coherency in another place.**

Now the long version

_Keypoints :_

K1. As of today, **some of the RADIUSS member projects are mature in there development and release processes** (let’s take Spack and MFEM as examples).
These projects may have their own policies, or **conform to existing policies** (xSDK/IDEAS).
These projects may be part of sdks/toolkits/bundles providing **convenient and coherent installations** (xSDK/E4S/CEED).

K2. One of the hot feature expected with the RADIUSS project is to enhance continuous integration with the opportunity to **automate testing on LC clusters**.
A related goal is to ease the deployment on LC clusters.

K3. Another important goal is to provide help to projects with less mature development and release processes so that they can benefit from and share good practices.

K4. Tools within the RADIUSS scope may not share the same usage perimeter (development, benching, research) or the same build context (station, cluster, python, compiler), and focusing on an unique RADIUSS instance built under the almighty coherency constraint may have us missing our point.

_Remarks :_

R1. There are several practice examples that could easily be shared and have a positive impact.
Projects relying on BLT use **host-config files in development context**.
**In a deployment context, Uberenv** is an interesting attempt in automating the usage of host-config files (also in a spack installation context).

_Suggestions :_

S1. In my opinion and based of the little knowledge I have from the situation, the actions taken now should aim at **ease and document the process of getting some projects into GitLab CI** in order to complete their Development and Release mechanisms with architecture aware automated testing.

S2. The informations display on the RADIUSS pages should reflect **the status of the project** rather than the final goal. Status information is useful in order to identify the next steps to focus on, and give practical information on the tools and libs. 
In this sense I like the "categories" on the RADIUSS page and the "pull request" and "issues" statistics of the explore page.
I personally think that build system, packaging, membership in a public sdk, and dependency to other RADIUSS tools and libs would be useful information to have.
Of course, automated gathering of these information would be a plus.
