### ISSUE TITLE
RADIUSS main page : Add a way to quickly get a short description of a product

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/llnl.github.io#243]
I think the current layout of the RADIUSS main page is great because it allows to quickly sort the products in categories.

Maybe what we need next is a way to quickly get a short description of a product without leaving the page. This way, I could find which product in "data management & viz" is most likely to fit my needs without leaving the page.

The description could be the same as the one used in the "all products" page, i.e. the github repo description.

One possible way to achieve it would be to have the description appearing when we leave the cursor on a product (where “name” appears). The main drawback I see here is the delay before the tooltip appears.

**Comment by hauten** [comment]
@LRWeber Would you be able to take a look at this? Discussed with Ian & landed on this:

When you roll over a repo's name, instead of the alt text "Name" (see attached screen shot), you should see `{{ repo.description }}` instead. The description might not be pulled into the data populating this view of the catalog...? Want to do this on *both* the home page catalog view & the RADIUSS catalog. (The category-by-category browse of the catalog already exposes repo descriptions on the "card" view.) If a repo's description is empty, perhaps "Repo name" is more helpful alt text than simply "Name."

![rollover](https://user-images.githubusercontent.com/31740953/65173146-1561d180-da03-11e9-91a6-dffbd75a306f.png)

**Comment by LRWeber** [comment]
@hauten I'll see what I can do.

That view is already pulling the data from `explore/github-data/labReposInfo.json`, so the description should be easy enough to add.

Regarding the tooltip delay, I think this will be a good solution for now. In the future, we may consider a more custom mouse-over functionality, similar to the behavior on the [Explore page](https://software.llnl.gov/explore/) (though we cannot use the same D3 based solution here).

**Comment by hauten** [comment]
Nice, @LRWeber, thank you!!
