### ISSUE TITLE
Expose Axom (RADIUSS) components as sub-hierarchical "repos" if possible

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#280]
Explore whether this is possible & how to do it.

Per Rob: One thing I’d like to figure out how to do is handle the case when a repo contains multiple projects. Axom is like that – there’s 6 or 8 “app infrastructure” things in there that don’t get real visibility, but have their own documentation (see the “component user guides” at https://axom.readthedocs.io/en/develop/). Not a high priority, but I’m wondering if there are other examples like this where it might make sense to have the idea of a hierarchy? 

Axom
  Primal
  Quest
  Sidre

**Comment by IanLee1521** [comment]
@hauten is this finished now?

**Comment by LRWeber** [comment]
I don't think it has been worked on.
https://github.com/LLNL/llnl.github.io/pull/356#issuecomment-652097219

**Comment by hauten** [comment]
@IanLee1521 @LRWeber I'm not sure if this is possible. Axom's sub-repos are not in the LLNL org, and Axom is not its own org. So I don't know how we would get this info from the API/bot. Worth investigating, or close it?

**Comment by LRWeber** [comment]
I don't think it's worth manually wrangling this level of data. We can't be expected to construct specialized code for every project's unique approach to organizing their work.

If a single repo project wants to highlight sub components, they can manage doing so themselves through their primary README, or, if they want some of that info displayed on our webpages, through their repo description.

Otherwise, to leverage our additional GitHub API based data analysis capabilities, they would need to make the decision to split into multiple repos.
