### ISSUE TITLE
Improvements to Radiuss P&G

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/llnl.github.io#332]
- Use anchors as suggested [here](https://github.com/LLNL/llnl.github.io/pull/236#pullrequestreview-379874003)
- Update section badges index consistently with the subsection (bui -> bld)
- Add missing links (e.g. references to xsdk)

**Comment by adrienbernede** [comment]
Please assign me :)

**Comment by adrienbernede** [comment]
@IanLee1521 could you please clarify what was your suggestion [there](https://github.com/LLNL/llnl.github.io/pull/236#pullrequestreview-379874003)

I looked and anchors seem to work only for in-file references. In addition the links currently set, though not working in markdown, make things work on the web page, right?

**Comment by IanLee1521** [comment]
Sure... My thought was that on this page https://software.llnl.gov/radiuss/policies/ that the links to specific points (e.g. `R.tes 6`) would like to that specific bullet on https://software.llnl.gov/radiuss/policies/tests-ci/ rather than to the top page.

On those target pages, if they are markdown headers then the anchor link would be generated automatically.

**Comment by adrienbernede** [comment]
OK, I think I see:
Making the bullet an anchor on the target page will give me a link that I can use on the index page to point directly at the given bullet.
I’ll try that.
