### ISSUE TITLE
OrderBy Stargazers

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#45]
Looks like #42 caused an unexpected side effect of now sorting by name instead of by number of stargazers. We should sort (at least be default) on stargazers.

This might possibly need a custom order function (e.g. https://stackoverflow.com/a/25375166).

**Comment by LRWeber** [comment]
Whoops. That's on me.

It wasn't really unexpected; I hadn't figured out what the original sorting method was, and the new method of loading data had everything ordered alphabetically according to `nameWithOwner`, e.g. "LLNL/llnl.github.io" since those were the keys in the order they were read.

I then intentionally ordered them by their base name, since I figured it at least made more sense.
Should be a quick fix.

**Comment by IanLee1521** [comment]
No worries!

I think ordering the data in the JSON by name makes a lot of sense. that will better isolate changes to the ordering over time, and cut down on the size of the Git repo.

As a related point to this, if we're looking at "custom" orderBy fields, maybe we should also start thinking about having some different "sort by" buttons to look at it in different ways.

**Comment by LRWeber** [comment]
I think that would be a worthwhile feature! Definitely something to add to the list.

**Comment by LRWeber** [comment]
Should be fixed by #46
