### ISSUE TITLE
Issue with symbols on at least the main page

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/llnl.github.io#488]
I was looking at the software.llnl.gov site and I ran into this problem with the symbols:
![image](https://user-images.githubusercontent.com/29114346/105780419-45898080-5f25-11eb-8577-5fcff681decb.png)

Is this a known issue?

I am running Windows 10 and using Chrome.

**Comment by LRWeber** [comment]
Looks like a problem loading some content from cdn.llnl.gov outside the LLNL network. (Works fine on-site / over VPN.)
@IanLee1521 I feel like we've seen an issue like this before, any thoughts?
![image](https://user-images.githubusercontent.com/29315109/105788305-12e78400-5f35-11eb-84ae-70558c797810.png)

**Comment by hauten** [comment]
Symbols show up on my phone (no VPN).

Font awesome v4.7.0 is old. That might not be the problem, but I can at least update the icons to a newer version.

**Comment by LRWeber** [comment]
The symbols are still missing on mine. (You may want to double check that you've cleared the cache so it's trying to re-download them.)

The transition from Font Awesome 4 to 5 was more involved, not just a matter of changing out the library, so we held off on that. I doubt that's the issue, especially since we've been hosting it ourselves all this time.

**Comment by LRWeber** [comment]
I found a more informative error message saying it's due to a "cross-origin resource sharing error". Sounds like a repeat of the issue we found before (https://github.com/LLNL/llnl.github.io/issues/34#issuecomment-325469839), which would mean something needs changing on the CDN side.

@IanLee1521 Can we ask the cdn.llnl.gov webmaster to look into this again?

**Comment by LRWeber** [comment]
@IanLee1521 The problem seems to have gotten worse; As of now, the LLNL CDN cannot be reached from outside the firewall at all, and our portal is completely non-functional.

**Comment by aidan-epperly** [comment]
> @IanLee1521 The problem seems to have gotten worse; As of now, the LLNL CDN cannot be reached from outside the firewall at all, and our portal is completely non-functional.

I am getting this behavior as well.

**Comment by LRWeber** [comment]
Most functionality appears to be restored, but the icon issue persists.

**Comment by LRWeber** [comment]
Should be resolved by #495
