### ISSUE TITLE
Repo Creation History Dates

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#62]
It looks like the mouseover text for the dates on the Repo Creation History graph is broken. Maybe this happened when we re-factored that functionality?

As a related request, would it look reasonable to have the date on the line itself? so something like:

"GitHub Founded: 2008-02-08"

?

**Comment by LRWeber** [comment]
Yes, the tool tips were removed during that #54 change. It was functionality unique to that particular graph that I removed in order to allow for a universal function.

I think in this case, it would make sense to simply add the date to the line label. It's unlikely that the labels will start running into the data, and it was tricky to trigger the mouseover for the thin lines anyway.
