### ISSUE TITLE
Handling of None 

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/llnl.github.io#85]
I just ran into this issue with None objects.. Not sure which level has the none that is erroring out. 

@LRWeber, have you ever run into this?

```
...

'LLNL/Collabmaps'
    page 1
    Modifying query...
    Query ready!
    Sending GraphQL query...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   326  100   165  100   161     23     22  0:00:07  0:00:07 --:--:--     1
    Checking response...
    HTTP/1.1 200 OK
    Data recieved!
/Users/lee1001/projs/llnl/llnl.github.io/explore/scripts/helpers.py:103: Warning: [{"message": "Something went wrong while executing your query. Please include `EDDE:7530:47E56A:5C0BE2:5ABE81AC` when reporting this issue."}]
  warnings.warn(json.dumps(outObj["errors"]), Warning)
    {"limit": 5000, "remaining": 4648, "reset": 1522437921}
Traceback (most recent call last):
  File "get_repos_users.py", line 61, in <module>
    for user in outObj["data"]["repository"]["mentionableUsers"]["nodes"]:
TypeError: 'NoneType' object is not subscriptable
FAILED - get_repos_users.py
```

**Comment by LRWeber** [comment]
Examining this issue has prompted another question:
What does the GraphQL API's "mentionableUsers" data actually track?

LLNL/Collabmaps has 1 contributor, 2 commits, 2 watchers, no forks, no additional branches, no issues or pull requests. And yet, our latest data indicates 117 lab users with this repo listed under their "contributedLabRepositories".
It doesn't just count every lab user as "mentionable" (there were 162 at the time of the data list I'm looking at). But it clearly counts more than just direct contributors.

This may need further investigation.

**Comment by IanLee1521** [comment]
Interesting... Per https://developer.github.com/v4/reference/object/repository/#mentionableusers it says "A list of Users that can be mentioned in the context of the repository."

I'm still not sure what that number means, but that's at least the definition... maybe @jbjonesjr can shed some light?

**Comment by LRWeber** [comment]
The error message itself seems to indicate that something went wrong with the query on GitHub's side in a way that wasn't just some communication error (it still returned the "200 OK" code). In this case, the query response then contains an "error" section.

This was supposed to be handled by [this line of code](https://github.com/LLNL/llnl.github.io/blob/03b39df8c61bb9267212f61c88f867a19606735a/explore/scripts/get_repos_users.py#L55), but it looks like that syntax only works in Python 2. We've just been lucky not to hit any odd GitHub glitches since the shift to Python 3!

I'll update those lines.

**Comment by LRWeber** [comment]
Correction: because the "errors" section [gets added by the helper in every case, replaced with a True/False value](https://github.com/LLNL/llnl.github.io/blob/03b39df8c61bb9267212f61c88f867a19606735a/explore/scripts/helpers.py#L124), the syntax should work just fine.

I thought this might instead have been introduced after we added collection of lab contributions for lab users. Two collections of data are built off the same query, but only one was set to properly exclude partial data for repos that encounter the occasional GitHub-side query failure.
I'm fixing this issue, though it does not seem to be the source of the crash.

**Comment by jbjonesjr** [comment]
So mentionable users is what powers the `@mention` in issues, prs, and such. How it knows who should be in that drop down list. 

### Based on my code understanding...

This should be (pretty much, save a few edge cases here and there) ALL organization members who have read access to the repo and are **NOT** suspended or spammy, unioned with all users who have made contributions into that repository (who are not suspended, spammy)

**Comment by LRWeber** [comment]
Hmm, if that's the case, then I don't think we can really get accurate date about lab member contributions.😟

**Comment by jbjonesjr** [comment]
if you're looking for contributors, i would iterate over the [commits](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository) and pull the author/commiters
